### PR TITLE
Add atb success screen

### PR DESCRIPTION
**Pull request by bsstoner**
Still a WIP, want to get feedback from people before merging.

@mrshu

### CODE REVIEW

**Comment by mrshu** [comment]
@bsstoner just wanted you to know that I very much like it and did the following to test it:

- ran `jpm run`
- opened `https://brian.duckduckgo.com/` very quickly
- saw the confetti screen

It pains me to see how much stuff did you have to include in order to make it run. If you would like to split it into separate files, do let me know -- that should also be possible.

**Comment by bsstoner** [comment]
@mrshu thanks for trying to split it out, I was wondering about that, it's not a huge deal though.

I think this is ready to go now. I added attribution for the confetti code. I also removed the setTimeout that we had previously added. I realized a more precise way to make sure they installed via duckduckgo.com is to check for the overlay div that I'm adding now when they click the "install" button. Let me know what you think.

Thanks!

**Comment by mrshu** [comment]
@bsstoner I got it working to the point when it showed some confetti, but it did not update them. Not sure why -- I hope this will not backfire =).

Thanks for removing that `setTimeout`, we might now also remove that require on the top of the file -- it is not used anywhere else.

If we are not adding the `#atb-extension-overlay` element at any other time, I think this is much better. 

Apart from that one line, it all looks good to me!

**Comment by bsstoner** [comment]
Good call, done!

**Comment by mrshu** [comment]
@bsstoner let's do it. With my luck, the review will still not let us through...

**Pull request merged**
